dotfiles_dir = "dev/dotfiles"

[settings]
posthooks = [
	"eww reload",
	"dunstctl reload",
	"systemctl --user daemon-reload"
]

[settings.dots]
templates = { source = "Templates", target = "Templates" }
scripts = { source = "scripts", target = "scripts" }

editorconfig = { source = "home/.editorconfig", target = ".editorconfig" }

electron = { source = "config/electron-flags.conf", target = ".config/electron-flags.conf" }
discord = { source = "config/electron-flags.conf", target = ".config/discord-flags.conf" }

git = { source = "git/config", target = ".config/git/config" }

# Also needs a `systemctl --user enable --now ip-geolocation.service` and `systemctl --user enable --now sunset.timer`
ip-geolocation = { source = "systemd/ip-geolocation.service", target = ".config/systemd/user/ip-geolocation.service" }
sunset-timer = { source = "systemd/sunset.timer", target = ".config/systemd/user/sunset.timer" }
sunset-service = { source = "systemd/sunset.service", target = ".config/systemd/user/sunset.service" }

btop = { source = "btop", target = ".config/btop" }
dunst = { source = "dunst", target = ".config/dunst" }
eww = { source = "eww", target = ".config/eww"}
fastfetch = { source = "fastfetch", target = ".config/fastfetch" }
gtk2 = { source = "gtk/gtk-2.0", target = ".config/gtk-2.0" }
gtk3 = { source = "gtk/gtk-3.0", target = ".config/gtk-3.0" }
gtk4 = { source = "gtk/gtk-4.0", target = ".config/gtk-4.0" }
gtk5 = { source = "gtk/gtk-5.0", target = ".config/gtk-5.0" }
gtk6 = { source = "gtk/gtk-6.0", target = ".config/gtk-6.0" }
hypr = { source = "hypr", target = ".config/hypr" }
kitty = { source = "kitty", target = ".config/kitty" }
lsd = { source = "lsd", target = ".config/lsd" }
lvim = { source = "lvim/config.lua", target = ".config/lvim/config.lua" }
rofi = { source = "rofi", target = ".config/rofi" }
steam = { source = "steam/steam_dev.cfg", target = ".steam/steam/steam_dev.cfg" }
swaylock = { source = "swaylock", target = ".config/swaylock" }
vim = { source = "vim/vimrc", target = ".config/vim/vimrc" }
yazi = { source = "yazi", target = ".config/yazi" }
zsh = { source = "zsh", target = ".config/zsh" }
