dotfiles_dir = "dev/dotfiles"

[settings]
posthooks = [ "i3-msg restart" ]

[settings.dots]
templates = { source = "Templates", target = "Templates" }
scripts = { source = "scripts", target = "scripts" }

